### ISSUE TITLE
"Caught a generic exception"

### ISSUE THREAD

**Issue by Kroc** [davidly/ntvcm#10]
Trying to use `ntvcm` on a creaky Core2Duo machine and it dies with a "caught a generic exception" error. Interestingly, as it's trying to print a CRLF perhaps?

![image](https://github.com/user-attachments/assets/6fea0c82-6c28-44f2-bda6-2c14216b4d58)

Here's the CPU-Z that indicates supported x86 extensions:

![image](https://github.com/user-attachments/assets/d59ebf43-d09c-480e-a1df-87c280af4b7a)

**Comment by davidly** [comment]
Thanks for reporting this bug!

Looks like the T5800 doesn't support the popcnt instruction, so I'm guessing that's the problem. Per https://www.cpu-world.com/Compare/149/Intel_Core_2_Duo_Mobile_T5800_vs_Intel_Core_i3_i3-4150.html

Try changing is_parity_even in x80.cxx to use the other line of code, instead of popcnt16.

**Comment by Kroc** [comment]
I don't know how you compile for Windows. I'm installing VS2022 atm, assuming that I can changes the compiler switches to limit CPU features to SSE2, however if you're using inline ASM then that wouldn't apply

**Comment by davidly** [comment]
Please reopen if this didn’t resolve the issue. Thanks!
